apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-nginx-deployment
  namespace: testkube-demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testkube.io/tier: backend
    spec:
      containers:
        - name: nginx
          image: yuliapjv/custom-nginx:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-nginx-service
  namespace: testkube-demo
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
