apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: curl-success
  namespace: testkube-demo
spec:
  steps:
    - name: Run curl
      container:
        image: curlimages/curl:8.7.1
      shell: curl -I --fail -s https://app.testkube.io || echo "Request failed"