apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: curl-success
spec:
  container:
    resources:
      requests:
        cpu: 32m
        memory: 32Mi
  steps:
    - name: Run tests
      parallel:
        matrix:
          url:
            [
                "https://testkube-test-page-lipsum.pages.dev/",
                "https://docs.testkube.io",
            ]
        shell: curl -f -LI '{{ matrix.url }}'
        container:
          image: curlimages/curl:8.7.1