apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflow
metadata:
  name: k6-failure-missing-env
  namespace: testkube-demo
  labels:
    core-tests: workflows
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube
      revision: main
      paths:
        - test/k6/executor-tests/k6-smoke-test.js
  container:
    resources:
      requests:
        cpu: 128m
        memory: 128Mi
    workingDir: /data/repo/test/k6/executor-tests
  steps:
    - name: Run test
      run:
        image: grafana/k6:0.43.1
        args:
          - run
          - k6-smoke-test.js