kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: postman-workflow-smoke-success
  namespace: testkube-demo
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube
      revision: main
      paths:
        - test/postman/executor-tests/postman-executor-smoke.postman_collection.json
  container:
    workingDir: /data/repo/test/postman/executor-tests
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
  steps:
    - name: Run test
      run:
        image: postman/newman:6-alpine
        args:
          - run
          - postman-executor-smoke.postman_collection.json
          - --env-var
          - TESTKUBE_POSTMAN_PARAM=TESTKUBE_POSTMAN_PARAM_value
status: {}