kind: TestWorkflow
apiVersion: testworkflows.testkube.io/v1
metadata:
  name: basic-postman-workflow
  namespace: testkube-demo
  labels:
    docs: example
spec:
  content:
    git:
      uri: https://github.com/kubeshop/testkube
      revision: main
      paths:
      - test/postman/executor-tests/postman-executor-smoke-without-envs.postman_collection.json
  container:
    workingDir: /data/repo/test/postman/executor-tests
    resources:
      requests:
        cpu: 256m
        memory: 128Mi
  steps:
  - name: Run test
    run:
      image: postman/newman:6-alpine
      args:
      - run
      - postman-executor-smoke-without-envs.postman_collection.json
status: {}
