apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
  namespace: testkube-demo
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: nginx-service
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: testkube-experiment-analysis
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: yuliapjv/custom-nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: testkube-demo
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: testkube-demo
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testkube.io/tier: backend
    spec:
      containers:
        - name: nginx
          image: yuliapjv/custom-nginx:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: testkube-demo
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-edge
    external-dns.alpha.kubernetes.io/cloudflare-proxied: 'false'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - argo-rollouts.testkube.dev
      secretName: argocd-rollouts-tls
  rules:
    - host: argo-rollouts.testkube.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service-stable
                port:
                  number: 80