apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-bluegreen
  namespace: testkube-demo
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: nginx-service
      previewService: nginx-service-preview
      autoPromotionEnabled: false
      prePromotionAnalysis:
        templates:
        - templateName: testkube-experiment-analysis
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - name: rollouts-demo
        image: yuliapjv/custom-nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80