apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: testkube-demo
spec:
  replicas: 2
  strategy:
    canary:
      analysis:
        templates:
          - templateName: testkube-experiment-analysis
      steps:
      - setWeight: 30
      - pause: {duration: 1m}
      - setWeight: 100
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollout-canary
        image: yuliapjv/custom-nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
