apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: testkube-demo
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 5}
      # The second step is the experiment which starts a single canary pod
      - experiment:
          duration: 2m
          templates:
          - name: canary
            specRef: canary
          # This experiment performs its own analysis by referencing an AnalysisTemplates
          # The success or failure of these runs will progress or abort the rollout respectively.
          analyses:
          - name: canary-experiment
            templateName: testkube-experiment-analysis
      - setWeight: 100
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollout-canary
        image: yuliapjv/custom-nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80