apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollout-canary
  namespace: testkube-demo
spec:
  replicas: 2
  strategy:
    canary:
      steps:
      - setWeight: 30
      - pause: {duration: 5}
#      - experiment:
#          duration: 2m
#          templates:
#          - name: canary # will launch a canary ReplicaSets and will run it for 2 min
#            specRef: canary
      analyses:
      - name: canary-experiment
        templateName: testkube-experiment-analysis
      - setWeight: 100
      - pause: {duration: 10}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-canary
  template:
    metadata:
      labels:
        app: rollout-canary
    spec:
      containers:
      - name: rollout-canary
        image: yuliapjv/custom-nginx:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-nginx-svc
spec:
  selector:
    app: rollout-experiment
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5000
  type: NodePort