apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: test-workflows
  namespace: argocd
  labels:
    argocd.argoproj.io/project: demo
spec:
  project: default
  source:
    repoURL: https://github.com/kubeshop/testkube-examples
    targetRevision: nginx-app-example
    path: ArgoCD
    directory:
      exclude: '{README.md}'
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jqPathExpressions:
        - .spec.metrics[].resource.name | select((. == "cpu") or (. == "memory"))
    - group: testworkflows.testkube.io
      kind: TestWorkflow
      jsonPointers:
        - /status
  destination:
    server: "https://kubernetes.default.svc"
    namespace: testkube-demo